"""Benutzer: passwort_hash hinzugefügt

Revision ID: 2c921cf84cb0
Revises: 732c6c387cae
Create Date: 2025-10-15 22:20:35.324062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c921cf84cb0'
down_revision = '732c6c387cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benutzer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passwort_hash', sa.String(length=200), nullable=False))
        batch_op.drop_column('passwort')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benutzer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passwort', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('passwort_hash')

    # ### end Alembic commands ###
